#!/usr/bin/env bash
set -euo pipefail

# This script intentionally writes one generated file; the heredoc expands only
# the validated release SHA. The publish directory is a fixed workflow input,
# but it is validated here because the helper is also a shipped control.
publish_dir="${1:-}"
sha="${2:-}"

if [[ -z "$publish_dir" || -z "$sha" ]]; then
  echo "usage: $0 <publish-dir> <8-64 hex release sha>" >&2
  exit 2
fi
if ! [[ "$publish_dir" =~ ^[A-Za-z0-9._/-]+$ ]] || [[ "$publish_dir" == /* || "$publish_dir" == *..* ]]; then
  echo "invalid publish directory: $publish_dir" >&2
  exit 2
fi
if ! [[ "$sha" =~ ^[0-9a-fA-F]{8,64}$ ]]; then
  echo "invalid release sha" >&2
  exit 2
fi
if [[ ! -d "$publish_dir" ]]; then
  echo "publish directory does not exist: $publish_dir" >&2
  exit 1
fi

target="$publish_dir/build-info.php"
# The unquoted heredoc is intentional: only the validated SHA is expanded into
# the generated PHP payload; the PHP variable is escaped below.
cat > "$target" <<PHP
<?php // build-stamp ${sha} -- auto-generated by deploy-static-site.yml, do not commit
if (PHP_SAPI !== 'cli' && !defined('CUBRIM_ENTRY')) {
    http_response_code(404);
    exit;
}
\$config['build_sha'] = '${sha}';
PHP
